server:
    port: 18083

spring:
    application:
        name: client-consumer

    cloud:
        consul:
          host: 127.0.0.1
          port: 8500
          discovery:
            health-check-path: /actuator/health
            health-check-interval: 5s
            register: false # 需要配置成false，否则系统启动的时候，会向consul注册一个服务

