server: 
    port: 8081
    
eureka: 
    client: 
        resister-with-eureka: false
        fetch-registry: false
        serviceUrl: 
            defaultZone: http://localhost:${server.port}/eureka/